# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import integrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_product_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('type', models.CharField(choices=[('core', 'Core set'), ('core-tfa', 'The Force Awakens core set')], default='core', max_length=25)),
            ],
            bases=(models.Model, integrations.models.XWingDataMixin),
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
            bases=(models.Model, integrations.models.XWingDataMixin),
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
            bases=(models.Model, integrations.models.XWingDataMixin),
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
            bases=(models.Model, integrations.models.XWingDataMixin),
        ),
        migrations.AlterUniqueTogether(
            name='damagedeck',
            unique_together=set([('name', 'type')]),
        ),
    ]
