# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import integrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20170218_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
    ]
