# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='products', to='rules.Source'),
        ),
    ]
