# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_auto_20170709_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ships',
            field=models.ManyToManyField(blank=True, related_name='products', to='integrations.Ship'),
        ),
    ]
