# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_product_ships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagedeck',
            name='type',
            field=models.CharField(choices=[('core', 'Core set'), ('core-tfa', 'The Force Awakens core set'), ('rebel-transport', 'Rebel Transport')], default='core', max_length=25),
        ),
    ]
