# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0045_source_file'),
        ('integrations', '0008_auto_20170726_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='card_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Rule'),
        ),
        migrations.AddField(
            model_name='damagedeck',
            name='card_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Rule'),
        ),
        migrations.AddField(
            model_name='pilot',
            name='card_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Rule'),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='card_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Rule'),
        ),
    ]
