# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_auto_20170726_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='card_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rules.Rule'),
        ),
        migrations.AlterField(
            model_name='damagedeck',
            name='card_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage_decks', to='rules.Rule'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='card_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pilots', to='rules.Rule'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='card_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='rules.Rule'),
        ),
    ]
