# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('slug', models.SlugField(default='', max_length=125, unique=True)),
                ('code', models.CharField(default='', max_length=25, unique=True)),
                ('version', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('slug', models.SlugField(default='', max_length=125, unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Rule')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='rules',
            field=models.ManyToManyField(through='books.SectionRule', to='rules.Rule'),
        ),
    ]
