# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rules', '0015_auto_20170323_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, default='', max_length=250)),
                ('alt_text', models.CharField(blank=True, default='', max_length=250)),
                ('file', models.FilePathField(blank=True, max_length=255, null=True, path='/home/lvisintini/src/xwing-rulebook/xwing_rulebook/static', recursive=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contents.Content')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_contents', to='contents.Image')),
            ],
            options={
                'verbose_name_plural': 'Image contents',
                'verbose_name': 'Image content',
            },
            bases=('contents.content',),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contents.Content')),
                ('content', models.TextField(default='')),
                ('keep_line_breaks', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='contents.Image')),
            ],
            options={
                'verbose_name_plural': 'Text contents',
                'verbose_name': 'Text content',
            },
            bases=('contents.content',),
        ),
        migrations.AddField(
            model_name='content',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_contents.content_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='content',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='rules.Source'),
        ),
    ]
