# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='preserve_title_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='content_as_per_source',
            field=models.TextField(blank=True, default='', help_text="If the text in the content field is not a verbatim copy of the source's text, Add the original text here."),
        ),
    ]
