# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0022_auto_20170327_2138'),
        ('contents', '0002_auto_20170327_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Used as the link identifier. Use <LINK:{alias}> in your markdown', max_length=50)),
                ('text', models.CharField(help_text='Only used if no rule is provided', max_length=255)),
                ('url', models.CharField(help_text='Used only if no rule is provided.', max_length=255)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='contents.TextContent')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.Rule')),
            ],
        ),
    ]
