# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(blank=True, default='', help_text='Only used if no rule is provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(blank=True, default='', help_text='Used only if no rule is provided.', max_length=255),
        ),
    ]
