# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20170406_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
