# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def move_forward(apps, schema_editor):
    Image = apps.get_model("contents", "Image")
    for i in Image.objects.all():
        i.file = i.file.replace(settings.STATICFILES_DIRS[0], '')
        i.save()


def move_backwards(apps, schema_editor):
    Image = apps.get_model("contents", "Image")
    for i in Image.objects.all():
        i.file = settings.STATICFILES_DIRS[0] + i.file
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_change_file_field_type'),
    ]

    operations = [
        migrations.RunPython(move_forward, move_backwards)
    ]
