# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_remove_root_dir_from_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='content',
        ),
    ]
