# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 12:57
from __future__ import unicode_literals

from django.db import migrations


def move_forward(apps, schema_editor):
    Link = apps.get_model("contents", "Link")
    done = []
    for l in Link.objects.all():
        if l.alias in done:
            l.delete()
            continue
        done.append(l.alias)


def move_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_remove_link_content'),
    ]

    operations = [
        migrations.RunPython(move_forward, move_backwards)
    ]
