# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_remove_duplicate_link_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='alias',
            field=models.CharField(help_text='Used as the link identifier. Use <LINK:{alias}> in your markdown', max_length=50, unique=True),
        ),
    ]
