# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 09:59
from __future__ import unicode_literals

from django.db import migrations


def move_forward(apps, schema_editor):
    TextContent = apps.get_model("contents", "TextContent")
    ImageContent = apps.get_model("contents", "ImageContent")
    TempContent = apps.get_model("contents", "TempContent")

    for ic in ImageContent.objects.iterator():
        TempContent(
            id=ic.content_ptr_id,
            type='image',
            title=ic.content_ptr.title,
            preserve_title_case=ic.content_ptr.preserve_title_case,
            source_id=ic.content_ptr.source_id,
            page=ic.content_ptr.page,
            content='',
            content_as_per_source='',
            keep_line_breaks=False,
            image_id=ic.image_id,
        ).save()

    for tc in TextContent.objects.iterator():
        TempContent(
            id=tc.content_ptr_id,
            type='text',
            title=tc.content_ptr.title,
            preserve_title_case=tc.content_ptr.preserve_title_case,
            source_id=tc.content_ptr.source_id,
            page=tc.content_ptr.page,
            content=tc.content,
            content_as_per_source=tc.content_as_per_source,
            keep_line_breaks=tc.keep_line_breaks,
            image_id=None,
        ).save()


def move_backwards(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_tempcontent'),
    ]

    operations = [
        migrations.RunPython(move_forward, move_backwards)
    ]
