# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0035_auto_20170510_2225'),
        ('contents', '0011_revert_polyphormic_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecontent',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='imagecontent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='content_ptr',
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='image',
        ),
        migrations.DeleteModel(
            name='ImageContent',
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
    ]
