# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_auto_20170511_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='polymorphic_ctype',
        ),
    ]
