# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_remove_content_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='content',
            name='content_as_per_source',
            field=models.TextField(blank=True, default='', help_text="If the text in the content field is not a verbatim copy of the source's text, Add the original text here."),
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.Image'),
        ),
        migrations.AddField(
            model_name='content',
            name='keep_line_breaks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=5),
        ),
    ]
