# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 10:03
from __future__ import unicode_literals

from django.db import migrations


def move_forward(apps, schema_editor):
    Content = apps.get_model("contents", "Content")
    TempContent = apps.get_model("contents", "TempContent")

    for tc in TempContent.objects.iterator():
        c = Content.objects.get(pk=tc.id)

        c.type = tc.type
        c.title = tc.title
        c.preserve_title_case = tc.preserve_title_case
        c.source_id = tc.source_id
        c.page = tc.page
        c.content = tc.content
        c.content_as_per_source = tc.content_as_per_source
        c.keep_line_breaks = tc.keep_line_breaks
        c.image_id = tc.image_id

        c.save()


def move_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_auto_20170511_1003'),
    ]

    operations = [
        migrations.RunPython(move_forward, move_backwards)
    ]
