# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_reload_contents_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempcontent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tempcontent',
            name='source',
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='contents.Image'),
        ),
        migrations.DeleteModel(
            name='TempContent',
        ),
    ]
