# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('text', 'Text'), ('item:ul', 'Unordered Item'), ('item:ol', 'Ordered Item'), ('image', 'Image'), ('table', 'Table')], default='item:ul', max_length=10)),
                ('expansion_related', models.BooleanField(default=False)),
                ('indentation', models.IntegerField(default=0)),
                ('ignore_title', models.BooleanField(default=False)),
                ('needs_revision', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['rule', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ClauseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Clause')),
            ],
            options={
                'ordering': ['active'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('content', models.TextField(default='')),
                ('page', models.IntegerField(blank=True, null=True)),
                ('keep_line_breaks', models.BooleanField(default=False)),
                ('file', models.FilePathField(blank=True, null=True, path='/home/lvisintini/src/xwing-rulebook/xwing_rulebook/static/assets', recursive=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('slug', models.SlugField(default='', max_length=125, unique=True)),
                ('expansion_rule', models.BooleanField(default=False)),
                ('related_topics', models.ManyToManyField(blank=True, related_name='_rule_related_topics_+', to='rules.Rule')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('date', models.DateField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=25, null=True)),
                ('code', models.CharField(default='', max_length=50, unique=True)),
                ('processed', models.BooleanField(default=False)),
                ('file', models.FilePathField(blank=True, max_length=255, null=True, path='/home/lvisintini/src/xwing-rulebook/xwing_rulebook/static/assets', recursive=True)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Source'),
        ),
        migrations.AddField(
            model_name='clausecontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.Content'),
        ),
        migrations.AddField(
            model_name='clause',
            name='available_contents',
            field=models.ManyToManyField(through='rules.ClauseContent', to='rules.Content'),
        ),
        migrations.AddField(
            model_name='clause',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='rules.Rule'),
        ),
    ]
