# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='version',
        ),
    ]
