# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_auto_20170114_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FilePathField(blank=True, null=True, path='/home/lvisintini/src/xwing-rulebook/xwing_rulebook/static', recursive=True),
        ),
    ]
