# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_auto_20170114_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clause',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('item:ul', 'Unordered Item'), ('item:ol', 'Ordered Item'), ('table', 'Table')], default='item:ul', max_length=10),
        ),
    ]
