# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_auto_20170114_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='huge_ship_rule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('rule', 'Rule'), ('rule-clarification', 'Rule clarification'), ('card-clarification', 'Card clarification'), ('example', 'Example')], default='rule', max_length=25),
        ),
    ]
