# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20170218_1625'),
        ('rules', '0007_auto_20170301_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='related_damage_deck',
            field=models.ManyToManyField(blank=True, related_name='related_damage_deck', to='integrations.DamageDeck'),
        ),
        migrations.AddField(
            model_name='rule',
            name='related_pilots',
            field=models.ManyToManyField(blank=True, related_name='related_rules', to='integrations.Pilot'),
        ),
        migrations.AddField(
            model_name='rule',
            name='related_upgrades',
            field=models.ManyToManyField(blank=True, related_name='related_rules', to='integrations.Upgrade'),
        ),
    ]
