# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_auto_20170306_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='related_rules',
            field=models.ManyToManyField(blank=True, related_name='_rule_related_rules_+', to='rules.Rule'),
        ),
    ]
