# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:31
from __future__ import unicode_literals

from django.db import migrations


def move_forward(apps, schema_editor):
    Rule = apps.get_model("rules", "Rule")
    for r in Rule.objects.all():
        for rt in r.related_topics.all():
            r.related_rules.add(rt)
        r.save()


def move_backwards(apps, schema_editor):
    Rule = apps.get_model("rules", "Rule")

    for r in Rule.objects.all():
        for rr in r.related_rules.all():
            r.related_topics.add(rr)
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_rule_related_rules'),
    ]

    operations = [
    ]

    operations = [
        migrations.RunPython(move_forward, move_backwards)
    ]
