# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_move_data_from_one_field_to_another'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='related_topics',
        ),
    ]
