# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_remove_rule_related_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FilePathField(blank=True, max_length=255, null=True, path='/home/lvisintini/src/xwing-rulebook/xwing_rulebook/static', recursive=True),
        ),
    ]
