# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_condition'),
        ('rules', '0012_auto_20170316_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='related_conditions',
            field=models.ManyToManyField(blank=True, related_name='related_rules', to='integrations.Condition'),
        ),
    ]
