# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0013_rule_related_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('rule', 'Rule'), ('rule-clarification', 'Rule clarification'), ('card-clarification', 'Card clarification'), ('card-errata', 'Card errata')], default='rule', max_length=25),
        ),
    ]
