# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0014_auto_20170321_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='alignment',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=6),
        ),
        migrations.AlterField(
            model_name='clause',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('item:ul', 'Unordered Item'), ('item:ol', 'Ordered Item'), ('table', 'Table'), ('image-block', 'Image (Block)'), ('image-wrap', 'Image (Wrap)')], default='item:ul', max_length=11),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('rule', 'Rule'), ('rule-clarification', 'Rule clarification'), ('card', 'Card'), ('card-clarification', 'Card clarification'), ('card-errata', 'Card errata')], default='rule', max_length=25),
        ),
    ]
