# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        ('rules', '0015_auto_20170323_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='clausecontent',
            name='new_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.Content'),
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.Image'),
        ),
    ]
