# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 10:17
from __future__ import unicode_literals
import re

from django.db import migrations


def move_forward(apps, schema_editor):
    r = re.compile(r'\[(.*?)\]')
    Image = apps.get_model("contents", "Image")
    Content = apps.get_model("rules", "Content")

    ContentType = apps.get_model('contenttypes', 'ContentType')
    TextContent = apps.get_model("contents", "TextContent")
    ImageContent = apps.get_model("contents", "ImageContent")
    tc_content_type = ContentType.objects.get_for_model(TextContent)
    ic_content_type = ContentType.objects.get_for_model(ImageContent)

    mapping = {}

    for c in Content.objects.all():
        i = None
        if c.file:
            i = Image(
                alt_text=','.join(r.findall(c.content)),
                file=c.file,
            )
            i.save()
            c.image = i
            c.save()
            c.clause_set.all().update(needs_revision=True)

        if '<FILE>' in c.content:
            ic = ImageContent(
                polymorphic_ctype=ic_content_type,
                title=c.title,
                source=c.source,
                page=c.page,
                image=i,
            )
            ic.save()
            mapping[c.id] = ic.id
        else:
            tc = TextContent(
                polymorphic_ctype=tc_content_type,
                title=c.title,
                source=c.source,
                page=c.page,
                content=c.content,
                keep_line_breaks=c.keep_line_breaks,
                image=i,
            )
            tc.save()
            mapping[c.id] = tc.id

    ClauseContent = apps.get_model("rules", "ClauseContent")

    for cc in ClauseContent.objects.all():
        cc.new_content_id = mapping[cc.content.id]
        cc.save()


def move_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        ('rules', '0016_new_fields'),
    ]

    operations = [
        migrations.RunPython(move_forward, move_backwards)
    ]
