# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0017_split_contents_in_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clausecontent',
            name='content',
        ),
        migrations.AlterField(
            model_name='clause',
            name='available_contents',
            field=models.ManyToManyField(through='rules.ClauseContent', to='contents.Content'),
        ),
    ]
