# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0018_auto_20170324_1105'),
    ]

    operations = [
        migrations.RenameField('clausecontent', 'new_content', 'content'),
    ]
