# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0019_rename_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clausecontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.Content'),
        ),
    ]
