# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0020_auto_20170324_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='image',
        ),
        migrations.RemoveField(
            model_name='content',
            name='source',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
