# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0021_auto_20170324_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clause',
            name='alignment',
        ),
        migrations.AddField(
            model_name='rule',
            name='preserve_name_case',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clause',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('item:ul', 'Unordered Item'), ('item:ol', 'Ordered Item'), ('table', 'Table'), ('image', 'Image')], default='item:ul', max_length=11),
        ),
    ]
