# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0022_auto_20170327_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='group',
            field=models.IntegerField(choices=[(1, 'Main'), (2, 'Left'), (3, 'Right'), (4, 'Top'), (5, 'Bottom')], default=1, verbose_name='Layout'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('rule', 'Rule'), ('rule-clarification', 'Rule clarification'), ('card', 'Card')], default='rule', max_length=25),
        ),
    ]
