# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0024_auto_20170402_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clause',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('item:ul', 'Unordered Item'), ('item:ol', 'Ordered Item')], default='item:ul', max_length=11),
        ),
    ]
