# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0025_auto_20170406_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
