# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0026_change_file_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='file',
        ),
    ]
