# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0027_remove_source_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='related_conditions',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='related_damage_decks',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='related_pilots',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='related_upgrades',
        ),
    ]
