# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0034_rule_additional_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clausecontent',
            name='clause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_contents', to='rules.Clause'),
        ),
    ]
