# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0035_auto_20170510_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
