# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0038_auto_20170520_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('M', 'Manual'), ('RB', 'Rules Booklet'), ('RC', 'Reference Card'), ('RR', 'Rules Reference'), ('FAQ', 'FAQ')], default='RC', max_length=50),
        ),
    ]
