# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 13:02
from __future__ import unicode_literals

from django.db import migrations
from rules.constants import SOURCE_STATUS


def move_forward(apps, schema_editor):
    Source = apps.get_model("rules", "Source")
    mapping = {
        (True, True): SOURCE_STATUS.PENDING,
        (True, False): SOURCE_STATUS.PROCESSED,
        (False, True): SOURCE_STATUS.PENDING,
        (False, False): SOURCE_STATUS.MISSING,
    }

    for s in Source.objects.all():
        s.status = mapping[(s.processed, s.missing)]
        s.save()


def move_backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('rules', '0041_source_status'),
    ]

    operations = [
        migrations.RunPython(move_forward, move_backwards)
    ]



