# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0042_updated_sources_status_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='missing',
        ),
        migrations.RemoveField(
            model_name='source',
            name='processed',
        ),
    ]
