# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0043_auto_20170620_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not released yet'), (1, 'Processed'), (2, 'Pending'), (3, 'Missing source')], default=3),
        ),
    ]
