# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0044_auto_20170620_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
