# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0045_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
