# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0034_rule_additional_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('general', 'General'), ('actions-and-game-effects', 'Actions and game effects'), ('Combat', 'Combat'), ('attack-timing-chart', 'Timing chart for performing an attack'), ('missions', 'Missions'), ('movement', 'Movement'), ('range-measurement', 'Range measurement')], default='general', max_length=24)),
                ('question', models.TextField(default='')),
                ('answer', models.TextField(default='')),
                ('page', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('related_clauses', models.ManyToManyField(blank=True, to='rules.Clause')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='rules.Source')),
            ],
        ),
    ]
