# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_as_per_source',
            field=models.TextField(blank=True, default='', help_text="If the text in the answer field is not a verbatim copy of the source's text, Add the original text here."),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_as_per_source',
            field=models.TextField(blank=True, default='', help_text="If the text in the question field is not a verbatim copy of the source's text, Add the original text here."),
        ),
    ]
