# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0035_auto_20170510_2225'),
        ('faqs', '0002_auto_20170509_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='related_rules',
            field=models.ManyToManyField(blank=True, to='rules.Rule'),
        ),
    ]
