# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_faq_related_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='related_clauses',
            field=models.ManyToManyField(blank=True, related_name='faqs', to='rules.Clause'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='related_rules',
            field=models.ManyToManyField(blank=True, related_name='faqs', to='rules.Rule'),
        ),
    ]
