# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_auto_20170518_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='topic',
            field=models.CharField(choices=[('general', 'General'), ('actions-and-game-effects', 'Actions and game effects'), ('combat', 'Combat'), ('attack-timing-chart', 'Timing chart for performing an attack'), ('missions', 'Missions'), ('movement', 'Movement'), ('range-measurement', 'Range measurement')], default='general', max_length=24),
        ),
    ]
