# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=0)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.IntegerField(default=0)),
                ('related_topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Rule')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Source'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='rule.Rule'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='sources',
            field=models.ManyToManyField(related_name='paragraphs', through='rule.Reference', to='rule.Source'),
        ),
    ]
