# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='source',
            name='version',
            field=models.CharField(max_length=25),
        ),
    ]
