# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_auto_20161223_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='related_topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.Rule'),
        ),
    ]
