# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0003_auto_20161224_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='order',
        ),
    ]
