# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0004_remove_rule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
