# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0005_source_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='expansion_rule',
            field=models.BooleanField(default=False),
        ),
    ]
