# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0007_auto_20161224_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('version', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RuleBookRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Rule')),
                ('rule_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.RuleBook')),
            ],
        ),
        migrations.AddField(
            model_name='rulebook',
            name='rules',
            field=models.ManyToManyField(related_name='rule_books', through='rule.RuleBookRule', to='rule.Rule'),
        ),
    ]
