# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0009_auto_20161224_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraph',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='source',
            name='code',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='paragraph',
            unique_together=set([('rule', 'order')]),
        ),
    ]
