# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0010_auto_20161228_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='related_topics',
        ),
    ]
