# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0011_remove_rule_related_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='related_topics',
            field=models.ManyToManyField(related_name='_rule_related_topics_+', to='rule.Rule'),
        ),
    ]
