# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0013_auto_20161228_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='needs_revision',
            field=models.BooleanField(default=False),
        ),
    ]
