# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0016_auto_20161230_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulebook',
            name='code',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
    ]
