# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0017_rulebook_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['name']},
        ),
    ]
