# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0018_auto_20161230_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('content', models.TextField(default='')),
                ('rule_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.RuleBook')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('text', 'Text'), ('item:ul', 'Unordered Item'), ('item:ol', 'Ordered Item'), ('image', 'Image'), ('table', 'Table')], default='item:ul', max_length=10)),
                ('expansion_related', models.BooleanField(default=False)),
                ('indentation', models.IntegerField(default=0)),
                ('ignore_title', models.BooleanField(default=False)),
                ('needs_revision', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['rule', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ClauseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('content', models.TextField(default='')),
                ('page', models.IntegerField(blank=True, null=True)),
                ('keep_line_breaks', models.BooleanField(default=False)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_contents', to='rule.Clause')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Source')),
            ],
        ),
        migrations.CreateModel(
            name='SectionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('book_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.BookSection')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Rule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='clause',
            name='clause_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_clauses', to='rule.ClauseContent'),
        ),
        migrations.AddField(
            model_name='clause',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='rule.Rule'),
        ),
        migrations.AddField(
            model_name='booksection',
            name='rules',
            field=models.ManyToManyField(through='rule.SectionRule', to='rule.Rule'),
        ),
        migrations.AlterUniqueTogether(
            name='clause',
            unique_together=set([('rule', 'order')]),
        ),
    ]
