# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 20:28
from __future__ import unicode_literals
import re

from django.db import migrations


def paragraphs_to_clauses(apps, schema_editor):
    regex = re.compile(r'^\*\*(.*)?:\*\*')
    Rule = apps.get_model("rule", "Rule")
    Clause = apps.get_model("rule", "Clause")
    ClauseContent = apps.get_model("rule", "ClauseContent")

    for r in Rule.objects.all():
        for p in r.paragraphs.all():
            c = Clause(
                rule=r,
                order=p.order,
                type=p.format.get('type', 'text'),
                expansion_related=p.format.get('expansion_rule', False),
                needs_revision=p.needs_revision,
                indentation=p.format.get('level', 0),
            )
            c.save()

            reference = p.reference_set.first()

            clause_content = ClauseContent(
                clause=c,
                title=next(iter(regex.findall(p.text)), None),
                content=re.sub(regex, '', p.text).strip(),
                source=reference.source,
                page=reference.page,
                keep_line_breaks=p.format.get('keep_line_breaks', False)
            )

            clause_content.save()

            c.clause_content = clause_content
            c.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0019_auto_20170103_0042'),
    ]

    operations = [
        migrations.RunPython(paragraphs_to_clauses, do_nothing)
    ]
