# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 22:00
from __future__ import unicode_literals

from django.db import migrations


def rules_to_section(apps, schema_editor):
    Rule = apps.get_model("rule", "Rule")
    RuleBook = apps.get_model("rule", "RuleBook")
    BookSection = apps.get_model("rule", "BookSection")
    SectionRule = apps.get_model("rule", "SectionRule")

    sections = [
        'Introduction',
        'Glossary',
        'Optional Rules',
        'Credits',
        'Setup Diagram',
        'Quick Reference'
    ]

    rb = RuleBook.objects.first()

    for i in range(len(sections)):
        bs = BookSection(
            rule_book=rb,
            title=sections[i],
            order=i,
        )
        bs.save()

    introduction = BookSection.objects.get(title='Introduction')
    glossary = BookSection.objects.get(title='Glossary')

    order = 0
    for r in Rule.objects.filter(id__in=[1, 2, 3]).order_by('id'):
        SectionRule(
            book_section=introduction,
            rule=r,
            order=order
        ).save()
        order += 1

    order = 0
    for r in Rule.objects.exclude(id__in=[1, 2, 3]).order_by('name'):
        SectionRule(
            book_section=glossary,
            rule=r,
            order=order
        ).save()
        order += 1


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0020_paragraphs_to_clauses'),
    ]

    operations = [
        migrations.RunPython(rules_to_section, do_nothing)
    ]
