# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0021_add_rules_to_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paragraph',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='source',
        ),
        migrations.RemoveField(
            model_name='rulebookrule',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='rulebookrule',
            name='rule_book',
        ),
        migrations.RemoveField(
            model_name='rulebook',
            name='rules',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.DeleteModel(
            name='RuleBookRule',
        ),
    ]
