# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 03:29
from __future__ import unicode_literals

from django.db import migrations


def populate_clause_content_version(apps, schema_editor):
    Clause = apps.get_model("rule", "Clause")
    ClauseContentVersion = apps.get_model("rule", "ClauseContentVersion")

    for c in Clause.objects.all():
        ClauseContentVersion(
            clause=c,
            content=c.clause_content,
            active=1
        ).save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0023_auto_20170103_0335'),
    ]

    operations = [
        migrations.RunPython(populate_clause_content_version, do_nothing)
    ]
