# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0024_contents_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clause',
            name='clause_content',
        ),
    ]
