# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0026_auto_20170103_2012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clause',
            unique_together=set([]),
        ),
    ]
