# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0027_auto_20170103_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='description',
        ),
        migrations.AddField(
            model_name='clausecontent',
            name='file',
            field=models.FilePathField(blank=True, null=True, path='/home/lvisintini/src/xwing-rulebook/xwing_rulebook/static/assets', recursive=True),
        ),
        migrations.AddField(
            model_name='source',
            name='file',
            field=models.FilePathField(blank=True, null=True, path='/home/lvisintini/src/xwing-rulebook/xwing_rulebook/static/assets', recursive=True),
        ),
    ]
