# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0029_auto_20170104_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
