# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0030_auto_20170104_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
