# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0031_source_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
