# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0032_auto_20170105_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='version',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
