# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 02:37
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def create_slugs(apps, schema_editor):
    Rule = apps.get_model("rule", "Rule")
    RuleBook = apps.get_model("rule", "RuleBook")
    BookSection = apps.get_model("rule", "BookSection")

    for r in Rule.objects.all():
        r.slug = slugify(r.name)
        r.save()

    for rb in RuleBook.objects.all():
        rb.slug = slugify(rb.name)
        rb.save()

    for bs in BookSection.objects.all():
        bs.slug = slugify(bs.title)
        bs.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0034_auto_20170109_0236'),
    ]

    operations = [
        migrations.RunPython(create_slugs, do_nothing)
    ]
