# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0035_create_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksection',
            name='slug',
            field=models.SlugField(default='', max_length=125, unique=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='slug',
            field=models.SlugField(default='', max_length=125, unique=True),
        ),
        migrations.AlterField(
            model_name='rulebook',
            name='slug',
            field=models.SlugField(default='', max_length=125, unique=True),
        ),
    ]
