# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0037_migrate_to_other_apps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksection',
            name='rule_book',
        ),
        migrations.RemoveField(
            model_name='booksection',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='clause',
            name='available_contents',
        ),
        migrations.RemoveField(
            model_name='clause',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='clausecontent',
            name='source',
        ),
        migrations.RemoveField(
            model_name='clausecontentversion',
            name='clause',
        ),
        migrations.RemoveField(
            model_name='clausecontentversion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='related_topics',
        ),
        migrations.RemoveField(
            model_name='sectionrule',
            name='book_section',
        ),
        migrations.RemoveField(
            model_name='sectionrule',
            name='rule',
        ),
        migrations.DeleteModel(
            name='BookSection',
        ),
        migrations.DeleteModel(
            name='Clause',
        ),
        migrations.DeleteModel(
            name='ClauseContent',
        ),
        migrations.DeleteModel(
            name='ClauseContentVersion',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='RuleBook',
        ),
        migrations.DeleteModel(
            name='SectionRule',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
