ICONS = {
  # Actions
  "[Focus]": "xwing-miniatures-font xwing-miniatures-font-focus",
  "[Target Lock]": "xwing-miniatures-font xwing-miniatures-font-targetlock",
  "[Evade]": "xwing-miniatures-font xwing-miniatures-font-evade",
  "[Barrel Roll]": "xwing-miniatures-font xwing-miniatures-font-barrelroll",
  "[Boost]": "xwing-miniatures-font xwing-miniatures-font-boost",
  "[Cloak]": "xwing-miniatures-font xwing-miniatures-font-cloak",
  "[Slam]": "xwing-miniatures-font xwing-miniatures-font-slam",
  "[Rotate Arc]": "xwing-miniatures-font xwing-miniatures-font-rotatearc",
  "[Recover]": "xwing-miniatures-font xwing-miniatures-font-recover",
  "[Reinforce]": "xwing-miniatures-font xwing-miniatures-font-reinforce",
  "[Coordinate]": "xwing-miniatures-font xwing-miniatures-font-coordinate",
  "[Jam]": "xwing-miniatures-font xwing-miniatures-font-jam",

  # Attributes
  "[Unique]": "xwing-miniatures-font xwing-miniatures-font-unique",
  "[Attack]": "xwing-miniatures-font xwing-miniatures-font-attack",
  "[Attack 180]": "xwing-miniatures-font xwing-miniatures-font-attack-180",
  "[Attack Turret]": "xwing-miniatures-font xwing-miniatures-font-attack-turret",
  "[Attack Front-Back]": "xwing-miniatures-font xwing-miniatures-font-attack-frontback",
  "[Agility]": "xwing-miniatures-font xwing-miniatures-font-agility",
  "[Energy]": "xwing-miniatures-font xwing-miniatures-font-energy",
  "[Hull]": "xwing-miniatures-font xwing-miniatures-font-hull",
  "[Shield]": "xwing-miniatures-font xwing-miniatures-font-shield",

  # Factions
  "[Rebel Alliance]": "xwing-miniatures-font xwing-miniatures-font-rebel",
  "[Galactic Empire]": "xwing-miniatures-font xwing-miniatures-font-empire",
  "[Scum and Villany]": "xwing-miniatures-font xwing-miniatures-font-scum",
  "[Resistance]": "xwing-miniatures-font xwing-miniatures-font-rebel-outline",
  "[First Order]": "xwing-miniatures-font xwing-miniatures-font-firstorder",

  # Hits
  "[Hit]": "xwing-miniatures-font xwing-miniatures-font-hit",
  "[Critical Hit]": "xwing-miniatures-font xwing-miniatures-font-crit",

  # Maneuvers
  "[Turn Left]": "xwing-miniatures-font xwing-miniatures-font-turnleft",
  "[Bank Left]": "xwing-miniatures-font xwing-miniatures-font-bankleft",
  "[Stationary]": "xwing-miniatures-font xwing-miniatures-font-stop",
  "[Straight]": "xwing-miniatures-font xwing-miniatures-font-straight",
  "[Stop]": "xwing-miniatures-font xwing-miniatures-font-stop",
  "[Bank Right]": "xwing-miniatures-font xwing-miniatures-font-bankright",
  "[Turn Right]": "xwing-miniatures-font xwing-miniatures-font-turnright",
  "[Koiogran Turn]": "xwing-miniatures-font xwing-miniatures-font-kturn",
  "[Segnor's Loop Left]": "xwing-miniatures-font xwing-miniatures-font-sloopleft",
  "[Segnor's Loop Right]": "xwing-miniatures-font xwing-miniatures-font-sloopright",
  "[Tallon Roll Right]": "xwing-miniatures-font xwing-miniatures-font-trollright",
  "[Tallon Roll Left]": "xwing-miniatures-font xwing-miniatures-font-trollleft",
  "[IG88D Segnor's Loop Left]": "xwing-miniatures-font xwing-miniatures-font-ig88d-sloopleft",
  "[IG88D Segnor's Loop Right]": "xwing-miniatures-font xwing-miniatures-font-ig88d-sloopright",
  "[Reverse Straight]": "xwing-miniatures-font xwing-miniatures-font-reversestraight",
  "[Reverse Bank Left]": "xwing-miniatures-font xwing-miniatures-font-reversebankleft",
  "[Reverse Bank Right]": "xwing-miniatures-font xwing-miniatures-font-reversebankright",

  # Misc
  "[Rebel Player]": "xwing-miniatures-font xwing-miniatures-font-helmet-rebel",
  "[Empire Player]": "xwing-miniatures-font xwing-miniatures-font-helmet-imperial",
  "[Scum Player]": "xwing-miniatures-font xwing-miniatures-font-helmet-scum",
  "[Squad Point Cost]": "xwing-miniatures-font xwing-miniatures-font-squad-point-cost",
  "[Epic]": "xwing-miniatures-font xwing-miniatures-font-epic",

  # Overlays
  "[Overlay 180]": "xwing-miniatures-font xwing-miniatures-font-overlay-180",
  "[Overlay Turret]": "xwing-miniatures-font xwing-miniatures-font-overlay-turret",
  "[Overlay Front-Back]": "xwing-miniatures-font xwing-miniatures-font-overlay-frontback",

  # Ships
  "[X-Wing]": "xwing-miniatures-ship xwing-miniatures-ship-xwing",
  "[TIE Fighter]": "xwing-miniatures-ship xwing-miniatures-ship-tiefighter",
  "[Y-Wing]": "xwing-miniatures-ship xwing-miniatures-ship-ywing",
  "[TIE Advanced]": "xwing-miniatures-ship xwing-miniatures-ship-tieadvanced",
  "[YT-1300]": "xwing-miniatures-ship xwing-miniatures-ship-yt1300",
  "[Firespray-31]": "xwing-miniatures-ship xwing-miniatures-ship-firespray31",
  "[A-Wing]": "xwing-miniatures-ship xwing-miniatures-ship-awing",
  "[TIE Interceptor]": "xwing-miniatures-ship xwing-miniatures-ship-tieinterceptor",
  "[HWK-290]": "xwing-miniatures-ship xwing-miniatures-ship-hwk290",
  "[Lambda-Class Shuttle]": "xwing-miniatures-ship xwing-miniatures-ship-lambdaclassshuttle",
  "[B-Wing]": "xwing-miniatures-ship xwing-miniatures-ship-bwing",
  "[TIE Bomber]": "xwing-miniatures-ship xwing-miniatures-ship-tiebomber",
  "[GR-75 Medium Transport]": "xwing-miniatures-ship xwing-miniatures-ship-gr75mediumtransport",
  "[CR90 Corvette]": "xwing-miniatures-ship xwing-miniatures-ship-cr90corvette",
  "[Z-95 Headhunter]": "xwing-miniatures-ship xwing-miniatures-ship-z95headhunter",
  "[TIE Defender]": "xwing-miniatures-ship xwing-miniatures-ship-tiedefender",
  "[E-Wing]": "xwing-miniatures-ship xwing-miniatures-ship-ewing",
  "[TIE Phantom]": "xwing-miniatures-ship xwing-miniatures-ship-tiephantom",
  "[YT-2400]": "xwing-miniatures-ship xwing-miniatures-ship-yt2400freighter",
  "[VT-49 Decimator]": "xwing-miniatures-ship xwing-miniatures-ship-vt49decimator",
  "[StarViper]": "xwing-miniatures-ship xwing-miniatures-ship-starviper",
  "[M3-A Interceptor]": "xwing-miniatures-ship xwing-miniatures-ship-m3ainterceptor",
  "[Aggressor]": "xwing-miniatures-ship xwing-miniatures-ship-aggressor",
  "[IG-2000]": "xwing-miniatures-ship xwing-miniatures-ship-ig2000",
  "[Raider-class Corvette]": "xwing-miniatures-ship xwing-miniatures-ship-raiderclasscorvette",
  "[YV-666]": "xwing-miniatures-ship xwing-miniatures-ship-yv666",
  "[Kihraxz Fighter]": "xwing-miniatures-ship xwing-miniatures-ship-kihraxzfighter",
  "[K-Wing]": "xwing-miniatures-ship xwing-miniatures-ship-kwing",
  "[TIE Punisher]": "xwing-miniatures-ship xwing-miniatures-ship-tiepunisher",
  "[T-70 X-Wing]": "xwing-miniatures-ship xwing-miniatures-ship-t70xwing",
  "[TIE/fo Fighter]": "xwing-miniatures-ship xwing-miniatures-ship-tiefofighter",
  "[Gozanti-Class Cruiser]": "xwing-miniatures-ship xwing-miniatures-ship-gozanticlasscruiser",
  "[Attack Shuttle]": "xwing-miniatures-ship xwing-miniatures-ship-attackshuttle",
  "[VCX-100]": "xwing-miniatures-ship xwing-miniatures-ship-vcx100",
  "[TIE Adv. Prototype]": "xwing-miniatures-ship xwing-miniatures-ship-tieadvancedprototype",
  "[G-1A Starfighter]": "xwing-miniatures-ship xwing-miniatures-ship-g1astarfighter",
  "[JumpMaster 5000]": "xwing-miniatures-ship xwing-miniatures-ship-jumpmaster5000",
  "[ARC-170]": "xwing-miniatures-ship xwing-miniatures-ship-arc170",
  "[TIE/sf Fighter]": "xwing-miniatures-ship xwing-miniatures-ship-tiesffighter",
  "[Protectorate Starfighter]": "xwing-miniatures-ship xwing-miniatures-ship-protectoratestarfighter",
  "[Lancer-class Pursuit Craft]": "xwing-miniatures-ship xwing-miniatures-ship-lancerclasspursuitcraft",
  "[U-Wing]": "xwing-miniatures-ship xwing-miniatures-ship-uwing",
  "[TIE Striker]": "xwing-miniatures-ship xwing-miniatures-ship-tiestriker",
  "[Upsilon-class Shuttle]": "xwing-miniatures-ship xwing-miniatures-ship-upsilonclassshuttler",
  "[Quadjumper]": "xwing-miniatures-ship xwing-miniatures-ship-quadjumper",

  # Slots
  "[Elite]": "xwing-miniatures-font xwing-miniatures-font-elite",
  "[Astromech]": "xwing-miniatures-font xwing-miniatures-font-astromech",
  "[Torpedo]": "xwing-miniatures-font xwing-miniatures-font-torpedo",
  "[Missile]": "xwing-miniatures-font xwing-miniatures-font-missile",
  "[Cannon]": "xwing-miniatures-font xwing-miniatures-font-cannon",
  "[Turret]": "xwing-miniatures-font xwing-miniatures-font-turret",
  "[Bomb]": "xwing-miniatures-font xwing-miniatures-font-bomb",
  "[Crew]": "xwing-miniatures-font xwing-miniatures-font-crew",
  "[Salvaged Astromech]": "xwing-miniatures-font xwing-miniatures-font-salvagedastromech",
  "[System]": "xwing-miniatures-font xwing-miniatures-font-system",
  "[Title]": "xwing-miniatures-font xwing-miniatures-font-title",
  "[Modification]": "xwing-miniatures-font xwing-miniatures-font-modification",
  "[Illicit]": "xwing-miniatures-font xwing-miniatures-font-illicit",
  "[Cargo]": "xwing-miniatures-font xwing-miniatures-font-cargo",
  "[Hardpoint]": "xwing-miniatures-font xwing-miniatures-font-hardpoint",
  "[Team]": "xwing-miniatures-font xwing-miniatures-font-team",
  "[Tech]": "xwing-miniatures-font xwing-miniatures-font-tech",

  # Tokens
  "[Focus Token]": "xwing-miniatures-font xwing-miniatures-font-token-focus",
  "[Evade Token]": "xwing-miniatures-font xwing-miniatures-font-token-evade",
  "[Target Lock Token]": "xwing-miniatures-font xwing-miniatures-font-token-targetlock",
  "[Shield Token]": "xwing-miniatures-font xwing-miniatures-font-token-shield",
  "[Stress Token]": "xwing-miniatures-font xwing-miniatures-font-token-stress",
  "[Critical Hit Token]": "xwing-miniatures-font xwing-miniatures-font-token-crit",
  "[Ion Token]": "xwing-miniatures-font xwing-miniatures-font-token-ion",
  "[Cloak Token]": "xwing-miniatures-font xwing-miniatures-font-token-cloak",
  "[Tractor Beam Token]": "xwing-miniatures-font xwing-miniatures-font-token-tractorbeam",
  "[Cannot Attack Token]": "xwing-miniatures-font xwing-miniatures-font-token-cannotattack",
  "[Energy Token]": "xwing-miniatures-font xwing-miniatures-font-token-energy",
  "[Extra Munitions Token]": "xwing-miniatures-font xwing-miniatures-font-token-extramunitions",
  "[Reinforce Token]": "xwing-miniatures-font xwing-miniatures-font-token-reinforce"
}